import type {
  Course,
  CourseStudent,
  IRProject,
  BoardPost,
  Comment,
  Notification,
  TeamBuildingRequest,
  PaymentRecord,
  SettlementRecord,
  InvestmentProposal,
  AIRecommendation,
  DashboardStats,
  AdminMember,
  AdminBoard,
  CRMMessage,
  JobApplication,
  UserRole,
  CodeGroup,
  CommonCode,
  CourseRequest,
  CourseProposal,
  IdeaRequest,
  IdeaProposal,
  NotificationPreference,
  NotificationTemplate,
  NotificationLog,
  InstructorProfile,
} from "../../src/types";
import type { DatabaseSchema } from "../db.js";

// ─────────────────────────────────────────────────────────────
// 1. 회원 정보 (Members)
// - 필수 보존 회원 2인 (otter.oh@gmail.com, mahau.master@gmail.com)
// - 가상 회원 30인 (status: "가상활성", 2026년 1월~7월 가입 및 최근 활동)
// ─────────────────────────────────────────────────────────────

const SEED_MEMBERS: AdminMember[] = [
  // ── 필수 보존 회원 ──
  {
    id: "m-otter",
    name: "오승환",
    email: "otter.oh@gmail.com",
    roles: ["admin", "member"],
    joinDate: "2024-01-01",
    lastLogin: "2026-09-06",
    status: "활성",
    courseCount: 4,
    avatar: "",
  },
  {
    id: "m-mahau",
    name: "마하우",
    email: "mahau.master@gmail.com",
    roles: ["admin", "member"],
    joinDate: "2024-02-01",
    lastLogin: "2026-09-06",
    status: "활성",
    courseCount: 5,
    avatar: "",
  },

  // ── 가상 회원 30인 (status: "가상활성") ──
  { id: "m-v01", name: "김서준", email: "sj.kim@novatech.io", roles: ["member"], joinDate: "2026-01-12", lastLogin: "2026-08-28", status: "가상활성", courseCount: 3 },
  { id: "m-v02", name: "박지민", email: "jm.park@aistudio.kr", roles: ["member"], joinDate: "2026-01-18", lastLogin: "2026-09-02", status: "가상활성", courseCount: 4 },
  { id: "m-v03", name: "이도윤", email: "dy.lee@cloudnest.dev", roles: ["member"], joinDate: "2026-01-25", lastLogin: "2026-08-30", status: "가상활성", courseCount: 2 },
  { id: "m-v04", name: "정예은", email: "ye.jung@growthlab.co", roles: ["member"], joinDate: "2026-02-03", lastLogin: "2026-09-04", status: "가상활성", courseCount: 3 },
  { id: "m-v05", name: "최민재", email: "mj.choi@quantumbiz.com", roles: ["member"], joinDate: "2026-02-11", lastLogin: "2026-08-25", status: "가상활성", courseCount: 2 },
  { id: "m-v06", name: "강하은", email: "he.kang@designcraft.kr", roles: ["member"], joinDate: "2026-02-20", lastLogin: "2026-08-31", status: "가상활성", courseCount: 2 },
  { id: "m-v07", name: "윤시우", email: "sw.yoon@dataforge.ai", roles: ["member"], joinDate: "2026-03-02", lastLogin: "2026-09-01", status: "가상활성", courseCount: 3 },
  { id: "m-v08", name: "임수아", email: "sa.lim@marketloop.co", roles: ["member"], joinDate: "2026-03-15", lastLogin: "2026-08-27", status: "가상활성", courseCount: 2 },
  { id: "m-v09", name: "한지호", email: "jh.han@b2bworks.io", roles: ["member"], joinDate: "2026-03-22", lastLogin: "2026-08-29", status: "가상활성", courseCount: 2 },
  { id: "m-v10", name: "송채원", email: "cw.song@creativelab.net", roles: ["member"], joinDate: "2026-04-05", lastLogin: "2026-09-03", status: "가상활성", courseCount: 2 },
  { id: "m-v11", name: "조은우", email: "ew.cho@edutech.kr", roles: ["member"], joinDate: "2026-04-14", lastLogin: "2026-09-04", status: "가상활성", courseCount: 3 },
  { id: "m-v12", name: "신유진", email: "yj.shin@finflows.co", roles: ["member"], joinDate: "2026-04-28", lastLogin: "2026-08-24", status: "가상활성", courseCount: 2 },
  { id: "m-v13", name: "유건우", email: "gw.yoo@robotics.ai", roles: ["member"], joinDate: "2026-05-03", lastLogin: "2026-09-05", status: "가상활성", courseCount: 3 },
  { id: "m-v14", name: "백서아", email: "sa.baek@healthai.kr", roles: ["member"], joinDate: "2026-05-16", lastLogin: "2026-08-26", status: "가상활성", courseCount: 2 },
  { id: "m-v15", name: "고동현", email: "dh.ko@devsec.io", roles: ["member"], joinDate: "2026-05-25", lastLogin: "2026-09-02", status: "가상활성", courseCount: 3 },
  { id: "m-v16", name: "문지아", email: "ja.moon@agenthub.dev", roles: ["member"], joinDate: "2026-06-02", lastLogin: "2026-09-04", status: "가상활성", courseCount: 4 },
  { id: "m-v17", name: "노현우", email: "hw.noh@ventureflow.vc", roles: ["member"], joinDate: "2026-06-18", lastLogin: "2026-08-22", status: "가상활성", courseCount: 1 },
  { id: "m-v18", name: "배수현", email: "sh.bae@vivaai.com", roles: ["member"], joinDate: "2026-06-29", lastLogin: "2026-09-01", status: "가상활성", courseCount: 2 },
  { id: "m-v19", name: "류재원", email: "jw.ryu@saasfactory.io", roles: ["member"], joinDate: "2026-07-08", lastLogin: "2026-08-30", status: "가상활성", courseCount: 2 },
  { id: "m-v20", name: "서다은", email: "de.seo@bizgenesis.kr", roles: ["member"], joinDate: "2026-07-22", lastLogin: "2026-09-03", status: "가상활성", courseCount: 2 },
  { id: "m-v21", name: "권태양", email: "ty.kwon@deepcore.ai", roles: ["member"], joinDate: "2026-04-10", lastLogin: "2026-08-28", status: "가상활성", courseCount: 2 },
  { id: "m-v22", name: "장하린", email: "hr.jang@fintechlab.io", roles: ["member"], joinDate: "2026-04-20", lastLogin: "2026-08-29", status: "가상활성", courseCount: 2 },
  { id: "m-v23", name: "안우진", email: "wj.ahn@edgeai.tech", roles: ["member"], joinDate: "2026-05-02", lastLogin: "2026-09-01", status: "가상활성", courseCount: 2 },
  { id: "m-v24", name: "황보라", email: "br.hwang@brandflow.kr", roles: ["member"], joinDate: "2026-05-15", lastLogin: "2026-08-31", status: "가상활성", courseCount: 2 },
  { id: "m-v25", name: "남궁선", email: "ks.namgoong@cloudops.net", roles: ["member"], joinDate: "2026-05-28", lastLogin: "2026-09-04", status: "가상활성", courseCount: 2 },
  { id: "m-v26", name: "심다빈", email: "db.shim@uxpulse.co", roles: ["member"], joinDate: "2026-06-05", lastLogin: "2026-08-27", status: "가상활성", courseCount: 2 },
  { id: "m-v27", name: "탁민혁", email: "mh.tak@hyperchain.io", roles: ["member"], joinDate: "2026-06-15", lastLogin: "2026-08-29", status: "가상활성", courseCount: 2 },
  { id: "m-v28", name: "오채린", email: "cr.oh@vclink.com", roles: ["member"], joinDate: "2026-06-25", lastLogin: "2026-08-25", status: "가상활성", courseCount: 1 },
  { id: "m-v29", name: "구자형", email: "jh.koo@solopreneur.kr", roles: ["member"], joinDate: "2026-07-02", lastLogin: "2026-09-02", status: "가상활성", courseCount: 2 },
  { id: "m-v30", name: "진가람", email: "gr.jin@voiceflow.ai", roles: ["member"], joinDate: "2026-07-15", lastLogin: "2026-09-05", status: "가상활성", courseCount: 2 },
];

// ─────────────────────────────────────────────────────────────
// 1-2. 강사 프로필 및 이력 (Instructors - 독립 엔티티)
// ─────────────────────────────────────────────────────────────

const SEED_INSTRUCTORS: InstructorProfile[] = [
  {
    id: "inst-mahau",
    name: "마하우",
    title: "피지컬 AI 시스템 아키텍트 & 로보틱스 엔지니어",
    bio: "12년간 산업용 로봇 제어기 및 에지 AI 컴퓨팅 파이프라인을 설계해 온 전문가입니다. 실전 프로젝트 중심으로 주니어 엔지니어가 현장에서 즉시 개발할 수 있는 역량을 전달합니다.",
    avatar: "",
    rating: 4.9,
    reviewCount: 15,
    totalStudents: 15,
    externalStudentCount: 50,
    infographic: {
      experienceYears: 12,
      totalStudents: 65,
      satisfactionRate: 98,
      topKeywords: ["Physical AI", "ROS2", "임베디드", "PBL", "자율주행"],
      careerHighlights: [
        "전) 첨단 자율로봇 연구소 수석 아키텍트",
        "국내외 로봇 제어 특허 8건 보유",
        "PBL 기반 주니어 양성 과정 100% 수료 달성",
      ],
      certifiedBadge: "피지컬 AI 최고 전문 강사",
    },
    careerHistory: [
      "2023~현재: AX Foundly 로보틱스 & AI 시스템 총괄",
      "2018~2023: 모빌리티 테크 수석 엔지니어",
      "2014~2018: 산업용 로봇 제어 소프트웨어 개발팀장",
    ],
    courses: [],
    reviews: [],
  },
  {
    id: "inst-shoh",
    name: "오승환",
    title: "AX Foundly 대표 & 테크 리드",
    bio: "10년 이상의 풀스택 아키텍처 설계 및 AI 에이전틱 시스템 구축 전문 강사입니다. 프로토타입부터 실제 상용화까지 이르는 End-to-End 창업 파이프라인을 직접 코칭합니다.",
    avatar: "",
    rating: 4.9,
    reviewCount: 42,
    totalStudents: 128,
    externalStudentCount: 500,
    infographic: {
      experienceYears: 10,
      totalStudents: 628,
      satisfactionRate: 99,
      topKeywords: ["AI 에이전트", "풀스택", "린스타트업", "하네스", "클라우드"],
      careerHighlights: [
        "현) AX Foundly 대표 & 테크 리드",
        "전) 글로벌 유니콘 테크 기업 소프트웨어 아키텍트",
        "AI 에이전틱 개발 자동화 파이프라인(Harness) 설계 총괄",
      ],
      certifiedBadge: "AI 풀스택 창업 공인 마스터",
    },
    careerHistory: [
      "2024~현재: AX Foundly 대표 & AI 기술 총괄",
      "2020~2024: 글로벌 테크 유니콘 시니어 소프트웨어 엔지니어",
      "2016~2020: 클라우드 분산 시스템 아키텍트",
    ],
    courses: [],
    reviews: [],
  },
  {
    id: "inst-kdh",
    name: "고동현",
    title: "고성능 시스템 소프트웨어 아키텍트",
    bio: "대규모 분산 컴퓨팅 및 저지연 AI 서빙 인프라 전문가입니다. 이론에 머무르지 않고 실제 수천만 트래픽을 견디는 프로덕션 아키텍처를 전수합니다.",
    avatar: "",
    rating: 4.8,
    reviewCount: 28,
    totalStudents: 95,
    externalStudentCount: 200,
    infographic: {
      experienceYears: 11,
      totalStudents: 295,
      satisfactionRate: 97,
      topKeywords: ["대규모 분산처리", "C++", "Rust", "AI 서빙", "성능최적화"],
      careerHighlights: [
        "전) 초대형 빅테크 인프라 코어 엔지니어",
        "고성능 LLM 추론 가속화 오픈소스 메인테이너",
        "글로벌 분산 데이터베이스 코어 아키텍처 설계",
      ],
      certifiedBadge: "고성능 시스템 소프트웨어 최고 전문가",
    },
    careerHistory: [
      "2023~현재: 고성능 시스템 소프트웨어 컨설턴트",
      "2019~2023: 대규모 데이터 플랫폼 코어 테크 리드",
      "2015~2019: 시스템 성능 최적화 수석 연구원",
    ],
    courses: [],
    reviews: [],
  },
  {
    id: "inst-ksh",
    name: "김소현",
    title: "AI 비즈니스 & 스타트업 디렉터",
    bio: "다년간의 실무 AI 프로덕트 런칭 및 스타트업 인큐베이팅 경험을 바탕으로, 수강생들이 실제 시장에서 작동하는 비즈니스를 만들 수 있도록 1:1 밀착 코칭을 제공합니다.",
    avatar: "",
    rating: 4.9,
    reviewCount: 86,
    totalStudents: 340,
    externalStudentCount: 3000,
    infographic: {
      experienceYears: 9,
      totalStudents: 3340,
      satisfactionRate: 98,
      topKeywords: ["AI 프로덕트", "실전 린스타트업", "1:1 밀착 코칭", "IR 피칭", "BM 설계"],
      careerHighlights: [
        "전) 글로벌 테크 유니콘 AI PM 리드",
        "다수 생성형 AI 프로덕트 런칭 및 시리즈 A 투자 유치 총괄",
        "창업진흥원 및 주요 액셀러레이터 공식 스타트업 멘토",
      ],
      certifiedBadge: "AI 린스타트업 최고 전문 디렉터",
    },
    careerHistory: [
      "2023~현재: AI 스타트업 엑셀러레이팅 수석 디렉터",
      "2020~2023: 글로벌 생성형 AI 서비스 PM 리드",
      "2017~2020: 린스타트업 인큐베이터 시니어 컨설턴트",
    ],
    courses: [],
    reviews: [],
  },
];

// ─────────────────────────────────────────────────────────────
// 2. 교육/강의 (Courses - Lectomate 실데이터 6종 매핑)
// - 기간: 2026년 3월 ~ 8월 배정
// - 필수 회원 오승환/마하우가 강사 또는 수강생으로 전원 참여
// ─────────────────────────────────────────────────────────────

const SEED_COURSES: Course[] = [
  {
    id: "c-lecto-1",
    title: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트",
    description: "로봇 하드웨어 설계부터 임베디드 시스템 프로그래밍, 인공지능 기반 로봇 제어 및 시뮬레이션 기술까지 문제 해결 중심(PBL)으로 실습하는 14주 완성 집중 과정.",
    category: "AI 모델링",
    tags: ["PhysicalAI", "로보틱스", "PBL", "ROS2", "임베디드AI"],
    aiSummary: "하드웨어 설계와 임베디드 AI 로봇 제어를 결합한 산업 현장 투입형 PBL 실전 프로젝트",
    deliveryType: "hybrid",
    location: "서울시 강남구 테헤란로 152 강남파이낸스센터 18층 로보틱스 랩",
    liveMeetingUrl: "https://zoom.us/j/physical-ai-robotics-pbl",
    instructor: "마하우",
    instructorTitle: "로보틱스 하드웨어 & 임베디드 AI 총괄",
    instructorAvatar: "",
    price: 1290000,
    discountedPrice: 990000,
    thumbnail: "",
    rating: 4.9,
    reviewCount: 15,
    studentCount: 15,
    status: "종료",
    isEnrolled: true,
    progress: 100,
    schedule: {
      startDate: "2026-03-03",
      endDate: "2026-06-12",
      daysOfWeek: ["화", "목"],
      timeSlot: "19:00 ~ 22:00",
      totalSessions: 28,
      scheduleType: "stepping_stone",
    },
    instructorProfile: {
      id: "inst-mahau",
      name: "마하우",
      title: "피지컬 AI 시스템 아키텍트 & 로보틱스 엔지니어",
      bio: "12년간 산업용 로봇 제어기 및 에지 AI 컴퓨팅 파이프라인을 설계해 온 전문가입니다. 실전 프로젝트 중심으로 주니어 엔지니어가 현장에서 즉시 개발할 수 있는 역량을 전달합니다.",
      avatar: "",
      rating: 4.9,
      reviewCount: 15,
      totalStudents: 15,
      infographic: {
        experienceYears: 12,
        totalStudents: 15,
        satisfactionRate: 98,
        topKeywords: ["Physical AI", "ROS2", "임베디드", "PBL", "자율주행"],
        careerHighlights: [
          "전) 첨단 자율로봇 연구소 수석 아키텍트",
          "국내외 로봇 제어 특허 8건 보유",
          "PBL 기반 주니어 양성 과정 100% 수료 달성",
        ],
        certifiedBadge: "피지컬 AI 최고 전문 강사",
      },
      careerHistory: [
        "2023~현재: AX Foundly 로보틱스 & AI 시스템 총괄",
        "2018~2023: 모빌리티 테크 수석 엔지니어",
        "2014~2018: 산업용 로봇 제어 소프트웨어 개발팀장",
      ],
      courses: [],
      reviews: [],
    },
    curriculum: [
      { week: 1, sessionNumber: 1, title: "로봇 하드웨어 기구 설계 및 3D 프린팅 기초", description: "PBL 프레임워크와 로봇 기본 구조 실습", duration: "3시간", deliveryType: "offline" },
      { week: 2, sessionNumber: 3, title: "아두이노 & 임베디드 C++ 센서 인터페이스", description: "모터 드라이버 및 센서 데이터 수집", duration: "3시간", deliveryType: "hybrid" },
      { week: 6, sessionNumber: 11, title: "ROS2 기반 노드 통신과 로봇 좌표계 변환", description: "실시간 분산 시스템 아키텍처", duration: "3시간", deliveryType: "online" },
      { week: 10, sessionNumber: 19, title: "비전 AI 기반 객체 인식 및 그리퍼 매니퓰레이션", description: "YOLO + Depth 카메라 융합 제어", duration: "3시간", deliveryType: "hybrid" },
      { week: 14, sessionNumber: 28, title: "PBL 자율 미션 최종 데모 피칭 및 코드 리뷰", description: "종합 실전 프로젝트 시연 및 평가", duration: "3시간", deliveryType: "offline" },
    ],
    reviews: [
      { id: "rev-1", author: "오승환", avatar: "", rating: 5, content: "이론과 실물 하드웨어 실습이 유기적으로 연결되어 현업 임베디드 AI 구축에 결정적인 통찰을 얻었습니다.", date: "2026-06-15" },
      { id: "rev-2", author: "유건우", avatar: "", rating: 5, content: "PBL 방식으로 진행되어 막히는 부분을 강사님께서 즉시 1:1 디버깅해 주셔서 큰 도움이 되었습니다.", date: "2026-06-14" },
    ],
  },
  {
    id: "c-lecto-2",
    title: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps",
    description: "단편적인 프롬프트 작성을 넘어 고급 RAG, 자율 AI 에이전트 설계, 그리고 상용 프로덕션 배포(MLOps)까지 아우르는 AI 엔지니어링 풀스택 실무 완성 코스.",
    category: "개발·IT",
    tags: ["AI엔지니어링", "RAG", "AIAgent", "MLOps", "FastAPI"],
    aiSummary: "RAG 파이프라인부터 자율 에이전트 오케스트레이션과 MLOps 배포까지 AI 엔지니어링 풀스택",
    deliveryType: "online",
    liveMeetingUrl: "https://zoom.us/j/ai-engineering-bootcamp-live",
    instructor: "오승환",
    instructorTitle: "AX Foundly 대표 & 테크 리드",
    instructorAvatar: "",
    price: 890000,
    discountedPrice: 690000,
    thumbnail: "",
    rating: 5.0,
    reviewCount: 19,
    studentCount: 19,
    status: "종료",
    isEnrolled: false,
    progress: 0,
    schedule: {
      startDate: "2026-04-06",
      endDate: "2026-05-29",
      daysOfWeek: ["월", "수"],
      timeSlot: "20:00 ~ 22:30",
      totalSessions: 16,
      scheduleType: "stepping_stone",
    },
    curriculum: [
      { week: 1, sessionNumber: 1, title: "모던 LLM 애플리케이션 아키텍처 이해", description: "API 오케스트레이션과 토큰 이코노미", duration: "2.5시간", deliveryType: "online" },
      { week: 3, sessionNumber: 5, title: "하이브리드 RAG & 벡터 DB 인덱싱 최적화", description: "BM25 + Dense Retriever 융합 실습", duration: "2.5시간", deliveryType: "online" },
      { week: 5, sessionNumber: 9, title: "함수 호출(Function Calling) 기반 AI 에이전트 구현", description: "외부 툴 연동 및 다단계 자율 실행", duration: "2.5시간", deliveryType: "online" },
      { week: 8, sessionNumber: 16, title: "MLOps 파이프라인 구축 및 컨테이너 상용 배포", description: "Docker, vLLM, 모니터링 대시보드 구축", duration: "2.5시간", deliveryType: "online" },
    ],
    reviews: [
      { id: "rev-3", author: "마하우", avatar: "", rating: 5, content: "단순 데모가 아니라 실제 트래픽과 예외 처리를 고려한 상용 수준의 RAG/에이전트 아키텍처를 배울 수 있는 최고의 강의입니다.", date: "2026-06-01" },
      { id: "rev-4", author: "박지민", avatar: "", rating: 5, content: "회사에서 진행하던 AI 신규 프로젝트에 바로 적용해서 성능과 응답 속도를 40% 개선했습니다.", date: "2026-05-30" },
    ],
  },
  {
    id: "c-lecto-3",
    title: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스",
    description: "모델 중심 접근에서 벗어나 인지 프레임워크, 정보 제어, 제어 흐름 및 메모리를 정교하게 설계하는 '하네스 중심(Harness-first)' 아키텍처 실무 구축 역량 함양.",
    category: "AI 모델링",
    tags: ["하네스엔지니어링", "HarnessFirst", "자가수정루프", "인식제어", "멀티에이전트"],
    aiSummary: "데이터 제어, 의사결정 체계, 오류 자가복구 메커니즘을 포괄하는 견고한 하네스 시스템 아키텍처",
    deliveryType: "online",
    liveMeetingUrl: "https://zoom.us/j/harness-engineering-masterclass",
    instructor: "오승환",
    instructorTitle: "하네스 중심 아키텍처 전문가",
    instructorAvatar: "",
    price: 750000,
    discountedPrice: 590000,
    thumbnail: "",
    rating: 4.9,
    reviewCount: 18,
    studentCount: 18,
    status: "종료",
    isEnrolled: false,
    progress: 0,
    schedule: {
      startDate: "2026-05-11",
      endDate: "2026-07-15",
      daysOfWeek: ["월", "수"],
      timeSlot: "19:30 ~ 21:30",
      totalSessions: 20,
      scheduleType: "stepping_stone",
    },
    curriculum: [
      { week: 1, sessionNumber: 1, title: "왜 하네스 엔지니어링인가: 모델의 한계를 극복하는 하네스 철학", description: "Harness-first 패러다임 분석", duration: "2시간", deliveryType: "online" },
      { week: 4, sessionNumber: 7, title: "단기/장기 메모리 제어와 상태 기계(State Machine) 설계", description: "상태 누수 방지 및 컨텍스트 격리", duration: "2시간", deliveryType: "online" },
      { week: 7, sessionNumber: 13, title: "오류 자가복구(Self-healing) 및 반복 개선 루프 구현", description: "Ralph-Loop 및 린트/테스트 자동 피드백", duration: "2시간", deliveryType: "online" },
      { week: 10, sessionNumber: 20, title: "프로덕션 하네스 벤치마크 및 신뢰도 검증 파이프라인", description: "실전 하네스 아키텍처 릴리즈", duration: "2시간", deliveryType: "online" },
    ],
    reviews: [
      { id: "rev-5", author: "마하우", avatar: "", rating: 5, content: "에이전트 개발에서 발생하는 환각과 멈춤 현상을 근본적으로 해결하는 시스템 하네스의 중요성을 절감했습니다.", date: "2026-07-16" },
      { id: "rev-6", author: "문지아", avatar: "", rating: 5, content: "하네스 설계 패턴을 적용하고 난 뒤 에이전트 자율 수행 성공률이 60%에서 95%로 수직 상승했습니다.", date: "2026-07-17" },
    ],
  },
  {
    id: "c-lecto-4",
    title: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화",
    description: "C++11/14/17/20 모던 C++ 핵심 기능, 템플릿 메타프로그래밍, STL 심화, 멀티스레딩 및 동시성 프로그래밍 기법을 학습하여 초고성능 시스템을 설계하는 역량 강화.",
    category: "개발·IT",
    tags: ["ModernC++", "C++20", "동시성프로그래밍", "시스템소프트웨어", "성능최적화"],
    aiSummary: "현대 C++20과 템플릿 메타프로그래밍, 멀티스레드 동시성 기법을 마스터하는 시스템 프로그래밍",
    deliveryType: "offline",
    location: "서울시 서초구 강남대로 311 드림플러스 5층 세미나실",
    instructor: "고동현",
    instructorTitle: "고성능 시스템 소프트웨어 아키텍트",
    instructorAvatar: "",
    price: 650000,
    discountedPrice: 490000,
    thumbnail: "",
    rating: 4.8,
    reviewCount: 12,
    studentCount: 12,
    status: "종료",
    isEnrolled: true,
    progress: 100,
    schedule: {
      startDate: "2026-06-01",
      endDate: "2026-07-24",
      daysOfWeek: ["월", "금"],
      timeSlot: "19:30 ~ 21:30",
      totalSessions: 16,
      scheduleType: "regular",
    },
    curriculum: [
      { week: 1, sessionNumber: 1, title: "현대 C++(C++17/20)의 스마트 포인터와 이동 의미론(Move Semantics)", description: "메모리 안전성과 RAII", duration: "2시간", deliveryType: "offline" },
      { week: 3, sessionNumber: 5, title: "템플릿 메타프로그래밍 & Concepts(C++20)", description: "컴파일 타임 연산 및 제약조건 설계", duration: "2시간", deliveryType: "offline" },
      { week: 6, sessionNumber: 11, title: "std::thread, std::async와 무잠금(Lock-free) 자료구조", description: "고성능 멀티스레드 동시성", duration: "2시간", deliveryType: "offline" },
      { week: 8, sessionNumber: 16, title: "SIMD 및 고성능 메모리 풀 최적화 실전 프로젝트", description: "대용량 처리 엔진 벤치마킹", duration: "2시간", deliveryType: "offline" },
    ],
    reviews: [
      { id: "rev-7", author: "오승환", avatar: "", rating: 5, content: "C++20 Concepts와 코루틴을 실전 시스템에 어떻게 접목해야 하는지 깊이 있는 해답을 얻었습니다.", date: "2026-07-25" },
      { id: "rev-8", author: "마하우", avatar: "", rating: 5, content: "임베디드 및 엣지 장치에서의 극한의 성능 튜닝에 직접적으로 활용할 수 있었습니다.", date: "2026-07-26" },
    ],
  },
  {
    id: "c-lecto-5",
    title: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지",
    description: "GitHub Copilot과 Jira API를 연동하여 이슈 요구사항 파싱부터 코드 브랜치 생성, AI 코드 작성, Pull Request(PR) 자동 발행까지 개발 생산성을 5배 끌어올리는 실전 워크플로우.",
    category: "개발·IT",
    tags: ["GitHubCopilot", "JiraAPI", "PR자동화", "CI/CD", "개발생산성"],
    aiSummary: "Jira 요구사항 파싱부터 AI 코드 생성 및 자동 PR 등록까지 완전 자동화된 엔지니어링 파이프라인",
    deliveryType: "online",
    liveMeetingUrl: "https://zoom.us/j/copilot-jira-workflow-live",
    instructor: "오승환",
    instructorTitle: "AI 데브옵스 & 생산성 컨설턴트",
    instructorAvatar: "",
    price: 490000,
    discountedPrice: 390000,
    thumbnail: "",
    rating: 4.9,
    reviewCount: 14,
    studentCount: 14,
    status: "종료",
    isEnrolled: false,
    progress: 0,
    schedule: {
      startDate: "2026-07-06",
      endDate: "2026-08-14",
      daysOfWeek: ["월", "수"],
      timeSlot: "20:00 ~ 22:00",
      totalSessions: 12,
      scheduleType: "stepping_stone",
    },
    curriculum: [
      { week: 1, sessionNumber: 1, title: "Jira REST API & 웹훅 이벤트 핸들링", description: "이슈 변경 실시간 감지 파이프라인", duration: "2시간", deliveryType: "online" },
      { week: 3, sessionNumber: 5, title: "Copilot 프롬프트 컨텍스트 엔지니어링 & 코드 템플릿", description: "티켓 명세 기반 테스트 코드 선행 생성", duration: "2시간", deliveryType: "online" },
      { week: 5, sessionNumber: 9, title: "GitHub Actions 연동 PR 자동화 & 린트/테스트 게이트", description: "CI 파이프라인 자가 치유 루프", duration: "2시간", deliveryType: "online" },
      { week: 6, sessionNumber: 12, title: "팀 단위 도입 전략과 개발 생산성 정량 측정", description: "DORA 메트릭스 향상 케이스 스터디", duration: "2시간", deliveryType: "online" },
    ],
    reviews: [
      { id: "rev-9", author: "마하우", avatar: "", rating: 5, content: "팀 온보딩 및 일상적인 티켓 처리 시간이 획기적으로 줄어들어 본질적인 코어 비즈니스 로직에 집중할 수 있게 되었습니다.", date: "2026-08-16" },
      { id: "rev-10", author: "이도윤", avatar: "", rating: 5, content: "Jira와 Copilot이 이렇게 유기적으로 엮일 수 있다는 게 놀라웠습니다. 바로 사내 팀에 도입했습니다.", date: "2026-08-15" },
    ],
  },
  {
    id: "c-lecto-6",
    title: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지",
    description: "변수, 포인터, 동적 메모리 할당, 구조체, 파일 입출력까지 컴퓨터의 동작 원리와 메모리 모델을 직접 체득하며 배우는 탄탄한 컴퓨터공학 기초 프로그래밍 코스.",
    category: "개발·IT",
    tags: ["C언어", "포인터", "메모리모델", "컴퓨터공학", "자료구조기초"],
    aiSummary: "포인터와 컴퓨터 메모리 구조를 완벽하게 정복하는 실습 중심 C 언어 프로그래밍 입문 과정",
    deliveryType: "online",
    liveMeetingUrl: "https://zoom.us/j/c-programming-fundamental",
    instructor: "마하우",
    instructorTitle: "컴퓨터공학 기초 및 시스템 프로그래밍 멘토",
    instructorAvatar: "",
    price: 390000,
    discountedPrice: 290000,
    thumbnail: "",
    rating: 4.8,
    reviewCount: 12,
    studentCount: 12,
    status: "종료",
    isEnrolled: true,
    progress: 100,
    schedule: {
      startDate: "2026-07-20",
      endDate: "2026-08-28",
      daysOfWeek: ["월", "수"],
      timeSlot: "19:00 ~ 21:00",
      totalSessions: 12,
      scheduleType: "regular",
    },
    curriculum: [
      { week: 1, sessionNumber: 1, title: "C 언어의 탄생과 컴파일러 동작 원리", description: "GCC 컴파일과 메모리 세그먼트", duration: "2시간", deliveryType: "online" },
      { week: 3, sessionNumber: 5, title: "포인터와 배열, 메모리 주소 체계의 완전 이해", description: "포인터 연산과 다중 포인터 시각화", duration: "2시간", deliveryType: "online" },
      { week: 4, sessionNumber: 8, title: "동적 메모리 할당(malloc/free)과 메모리 누수 방지", description: "Valgrind를 활용한 디버깅", duration: "2시간", deliveryType: "online" },
      { week: 6, sessionNumber: 12, title: "구조체와 연결 리스트(Linked List) 미니 프로젝트", description: "실전 자료구조 구현 및 최종 과제", duration: "2시간", deliveryType: "online" },
    ],
    reviews: [
      { id: "rev-11", author: "오승환", avatar: "", rating: 5, content: "고수준 언어를 쓰면서도 항상 가려웠던 메모리 하부의 실체를 명쾌하고 명료하게 정리해 준 명강의입니다.", date: "2026-08-29" },
      { id: "rev-12", author: "신유진", avatar: "", rating: 5, content: "비전공자에게 악명 높은 포인터를 그림과 디버거로 쉽게 설명해 주셔서 드디어 이해했습니다!", date: "2026-08-30" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────
// 3. 수강생 및 결제 연동 데이터 (CourseStudent & PaymentRecord)
// - 6개 강좌마다 12~19명 배정 (총 84건 수강 및 1:1 결제 완료)
// - 오승환: c-lecto-1, c-lecto-4, c-lecto-6 수강
// - 마하우: c-lecto-2, c-lecto-3, c-lecto-4, c-lecto-5 수강
// ─────────────────────────────────────────────────────────────

interface EnrolledSpec {
  courseId: string;
  courseTitle: string;
  userId: string;
  name: string;
  email: string;
  enrolledAt: string;
  amount: number;
  method: "카드" | "계좌이체" | "카카오페이";
  progress: number;
}

const ENROLLMENTS_DEF: EnrolledSpec[] = [
  // ── c-lecto-1 (피지컬 AI & 로보틱스, 강사: 마하우, 총 15명) ──
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-otter", name: "오승환", email: "otter.oh@gmail.com", enrolledAt: "2026-02-20", amount: 990000, method: "카드", progress: 100 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v13", name: "유건우", email: "gw.yoo@robotics.ai", enrolledAt: "2026-02-21", amount: 990000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v15", name: "고동현", email: "dh.ko@devsec.io", enrolledAt: "2026-02-22", amount: 990000, method: "카드", progress: 95 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v23", name: "안우진", email: "wj.ahn@edgeai.tech", enrolledAt: "2026-02-23", amount: 990000, method: "계좌이체", progress: 90 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v01", name: "김서준", email: "sj.kim@novatech.io", enrolledAt: "2026-02-24", amount: 990000, method: "카드", progress: 100 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v07", name: "윤시우", email: "sw.yoon@dataforge.ai", enrolledAt: "2026-02-25", amount: 990000, method: "카카오페이", progress: 85 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v11", name: "조은우", email: "ew.cho@edutech.kr", enrolledAt: "2026-02-25", amount: 990000, method: "카드", progress: 90 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v16", name: "문지아", email: "ja.moon@agenthub.dev", enrolledAt: "2026-02-26", amount: 990000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v03", name: "이도윤", email: "dy.lee@cloudnest.dev", enrolledAt: "2026-02-26", amount: 990000, method: "카드", progress: 85 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v25", name: "남궁선", email: "ks.namgoong@cloudops.net", enrolledAt: "2026-02-27", amount: 990000, method: "계좌이체", progress: 95 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v27", name: "탁민혁", email: "mh.tak@hyperchain.io", enrolledAt: "2026-02-27", amount: 990000, method: "카드", progress: 80 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v02", name: "박지민", email: "jm.park@aistudio.kr", enrolledAt: "2026-02-28", amount: 990000, method: "카드", progress: 100 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v14", name: "백서아", email: "sa.baek@healthai.kr", enrolledAt: "2026-02-28", amount: 990000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v21", name: "권태양", email: "ty.kwon@deepcore.ai", enrolledAt: "2026-03-01", amount: 990000, method: "카드", progress: 95 },
  { courseId: "c-lecto-1", courseTitle: "피지컬 AI 및 로보틱스 전문가 양성 과정: PBL 기반 실전 프로젝트", userId: "m-v29", name: "구자형", email: "jh.koo@solopreneur.kr", enrolledAt: "2026-03-01", amount: 990000, method: "카카오페이", progress: 85 },

  // ── c-lecto-2 (AI 엔지니어링 풀스택, 강사: 오승환, 총 19명) ──
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-mahau", name: "마하우", email: "mahau.master@gmail.com", enrolledAt: "2026-03-25", amount: 690000, method: "카드", progress: 100 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v02", name: "박지민", email: "jm.park@aistudio.kr", enrolledAt: "2026-03-26", amount: 690000, method: "카드", progress: 100 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v01", name: "김서준", email: "sj.kim@novatech.io", enrolledAt: "2026-03-26", amount: 690000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v07", name: "윤시우", email: "sw.yoon@dataforge.ai", enrolledAt: "2026-03-27", amount: 690000, method: "카드", progress: 95 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v16", name: "문지아", email: "ja.moon@agenthub.dev", enrolledAt: "2026-03-28", amount: 690000, method: "카드", progress: 100 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v03", name: "이도윤", email: "dy.lee@cloudnest.dev", enrolledAt: "2026-03-29", amount: 690000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v19", name: "류재원", email: "jw.ryu@saasfactory.io", enrolledAt: "2026-03-29", amount: 690000, method: "카드", progress: 85 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v04", name: "정예은", email: "ye.jung@growthlab.co", enrolledAt: "2026-03-30", amount: 690000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v05", name: "최민재", email: "mj.choi@quantumbiz.com", enrolledAt: "2026-03-30", amount: 690000, method: "계좌이체", progress: 95 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v08", name: "임수아", email: "sa.lim@marketloop.co", enrolledAt: "2026-03-31", amount: 690000, method: "카드", progress: 85 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v10", name: "송채원", email: "cw.song@creativelab.net", enrolledAt: "2026-03-31", amount: 690000, method: "카카오페이", progress: 80 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v11", name: "조은우", email: "ew.cho@edutech.kr", enrolledAt: "2026-04-01", amount: 690000, method: "카드", progress: 100 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v18", name: "배수현", email: "sh.bae@vivaai.com", enrolledAt: "2026-04-01", amount: 690000, method: "카드", progress: 90 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v21", name: "권태양", email: "ty.kwon@deepcore.ai", enrolledAt: "2026-04-02", amount: 690000, method: "카카오페이", progress: 95 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v22", name: "장하린", email: "hr.jang@fintechlab.io", enrolledAt: "2026-04-02", amount: 690000, method: "카드", progress: 85 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v24", name: "황보라", email: "br.hwang@brandflow.kr", enrolledAt: "2026-04-03", amount: 690000, method: "계좌이체", progress: 90 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v26", name: "심다빈", email: "db.shim@uxpulse.co", enrolledAt: "2026-04-03", amount: 690000, method: "카드", progress: 95 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v29", name: "구자형", email: "jh.koo@solopreneur.kr", enrolledAt: "2026-04-04", amount: 690000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-2", courseTitle: "AI 엔지니어링 풀스택 구현 부트캠프: 프롬프트, RAG, 에이전트 및 MLOps", userId: "m-v30", name: "진가람", email: "gr.jin@voiceflow.ai", enrolledAt: "2026-04-04", amount: 690000, method: "카드", progress: 100 },

  // ── c-lecto-3 (하네스 엔지니어링, 강사: 오승환, 총 18명) ──
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-mahau", name: "마하우", email: "mahau.master@gmail.com", enrolledAt: "2026-05-01", amount: 590000, method: "카드", progress: 100 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v16", name: "문지아", email: "ja.moon@agenthub.dev", enrolledAt: "2026-05-02", amount: 590000, method: "카드", progress: 100 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v01", name: "김서준", email: "sj.kim@novatech.io", enrolledAt: "2026-05-02", amount: 590000, method: "카카오페이", progress: 95 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v02", name: "박지민", email: "jm.park@aistudio.kr", enrolledAt: "2026-05-03", amount: 590000, method: "카드", progress: 100 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v07", name: "윤시우", email: "sw.yoon@dataforge.ai", enrolledAt: "2026-05-03", amount: 590000, method: "계좌이체", progress: 90 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v15", name: "고동현", email: "dh.ko@devsec.io", enrolledAt: "2026-05-04", amount: 590000, method: "카드", progress: 100 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v23", name: "안우진", email: "wj.ahn@edgeai.tech", enrolledAt: "2026-05-05", amount: 590000, method: "카카오페이", progress: 85 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v25", name: "남궁선", email: "ks.namgoong@cloudops.net", enrolledAt: "2026-05-05", amount: 590000, method: "카드", progress: 90 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v19", name: "류재원", email: "jw.ryu@saasfactory.io", enrolledAt: "2026-05-06", amount: 590000, method: "카드", progress: 95 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v04", name: "정예은", email: "ye.jung@growthlab.co", enrolledAt: "2026-05-06", amount: 590000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v06", name: "강하은", email: "he.kang@designcraft.kr", enrolledAt: "2026-05-07", amount: 590000, method: "카드", progress: 85 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v09", name: "한지호", email: "jh.han@b2bworks.io", enrolledAt: "2026-05-07", amount: 590000, method: "계좌이체", progress: 80 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v13", name: "유건우", email: "gw.yoo@robotics.ai", enrolledAt: "2026-05-08", amount: 590000, method: "카드", progress: 95 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v14", name: "백서아", email: "sa.baek@healthai.kr", enrolledAt: "2026-05-08", amount: 590000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v20", name: "서다은", email: "de.seo@bizgenesis.kr", enrolledAt: "2026-05-09", amount: 590000, method: "카드", progress: 85 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v26", name: "심다빈", email: "db.shim@uxpulse.co", enrolledAt: "2026-05-09", amount: 590000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v27", name: "탁민혁", email: "mh.tak@hyperchain.io", enrolledAt: "2026-05-10", amount: 590000, method: "카드", progress: 95 },
  { courseId: "c-lecto-3", courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스", userId: "m-v30", name: "진가람", email: "gr.jin@voiceflow.ai", enrolledAt: "2026-05-10", amount: 590000, method: "계좌이체", progress: 100 },

  // ── c-lecto-4 (고급 C++ 프로그래밍, 강사: 고동현, 총 12명) ──
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-otter", name: "오승환", email: "otter.oh@gmail.com", enrolledAt: "2026-05-22", amount: 490000, method: "카드", progress: 100 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-mahau", name: "마하우", email: "mahau.master@gmail.com", enrolledAt: "2026-05-23", amount: 490000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v13", name: "유건우", email: "gw.yoo@robotics.ai", enrolledAt: "2026-05-24", amount: 490000, method: "카드", progress: 95 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v23", name: "안우진", email: "wj.ahn@edgeai.tech", enrolledAt: "2026-05-24", amount: 490000, method: "계좌이체", progress: 90 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v25", name: "남궁선", email: "ks.namgoong@cloudops.net", enrolledAt: "2026-05-25", amount: 490000, method: "카드", progress: 85 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v27", name: "탁민혁", email: "mh.tak@hyperchain.io", enrolledAt: "2026-05-26", amount: 490000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v03", name: "이도윤", email: "dy.lee@cloudnest.dev", enrolledAt: "2026-05-27", amount: 490000, method: "카드", progress: 85 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v07", name: "윤시우", email: "sw.yoon@dataforge.ai", enrolledAt: "2026-05-28", amount: 490000, method: "카카오페이", progress: 95 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v12", name: "신유진", email: "yj.shin@finflows.co", enrolledAt: "2026-05-29", amount: 490000, method: "계좌이체", progress: 80 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v15", name: "고동현", email: "dh.ko@devsec.io", enrolledAt: "2026-05-30", amount: 490000, method: "카드", progress: 100 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v17", name: "노현우", email: "hw.noh@ventureflow.vc", enrolledAt: "2026-05-30", amount: 490000, method: "카카오페이", progress: 85 },
  { courseId: "c-lecto-4", courseTitle: "고급 C++ 프로그래밍 마스터 과정: 현대 C++와 시스템 프로그래밍 심화", userId: "m-v28", name: "오채린", email: "cr.oh@vclink.com", enrolledAt: "2026-05-31", amount: 490000, method: "카드", progress: 85 },

  // ── c-lecto-5 (Copilot과 Jira 연동, 강사: 오승환, 총 14명) ──
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-mahau", name: "마하우", email: "mahau.master@gmail.com", enrolledAt: "2026-06-25", amount: 390000, method: "카드", progress: 100 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v03", name: "이도윤", email: "dy.lee@cloudnest.dev", enrolledAt: "2026-06-26", amount: 390000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v04", name: "정예은", email: "ye.jung@growthlab.co", enrolledAt: "2026-06-27", amount: 390000, method: "카드", progress: 95 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v05", name: "최민재", email: "mj.choi@quantumbiz.com", enrolledAt: "2026-06-28", amount: 390000, method: "카드", progress: 90 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v06", name: "강하은", email: "he.kang@designcraft.kr", enrolledAt: "2026-06-29", amount: 390000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v08", name: "임수아", email: "sa.lim@marketloop.co", enrolledAt: "2026-06-30", amount: 390000, method: "카드", progress: 85 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v09", name: "한지호", email: "jh.han@b2bworks.io", enrolledAt: "2026-07-01", amount: 390000, method: "계좌이체", progress: 85 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v10", name: "송채원", email: "cw.song@creativelab.net", enrolledAt: "2026-07-02", amount: 390000, method: "카드", progress: 95 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v11", name: "조은우", email: "ew.cho@edutech.kr", enrolledAt: "2026-07-03", amount: 390000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v12", name: "신유진", email: "yj.shin@finflows.co", enrolledAt: "2026-07-03", amount: 390000, method: "카드", progress: 80 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v18", name: "배수현", email: "sh.bae@vivaai.com", enrolledAt: "2026-07-04", amount: 390000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v20", name: "서다은", email: "de.seo@bizgenesis.kr", enrolledAt: "2026-07-04", amount: 390000, method: "카드", progress: 95 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v22", name: "장하린", email: "hr.jang@fintechlab.io", enrolledAt: "2026-07-05", amount: 390000, method: "계좌이체", progress: 90 },
  { courseId: "c-lecto-5", courseTitle: "Copilot과 Jira 연동을 통한 개발 워크플로우 혁신: 티켓 분석부터 PR 생성 자동화까지", userId: "m-v24", name: "황보라", email: "br.hwang@brandflow.kr", enrolledAt: "2026-07-05", amount: 390000, method: "카드", progress: 85 },

  // ── c-lecto-6 (C 프로그래밍 기초, 강사: 마하우, 총 12명) ──
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-otter", name: "오승환", email: "otter.oh@gmail.com", enrolledAt: "2026-07-10", amount: 290000, method: "카드", progress: 100 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v12", name: "신유진", email: "yj.shin@finflows.co", enrolledAt: "2026-07-11", amount: 290000, method: "카카오페이", progress: 100 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v14", name: "백서아", email: "sa.baek@healthai.kr", enrolledAt: "2026-07-12", amount: 290000, method: "카드", progress: 95 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v18", name: "배수현", email: "sh.bae@vivaai.com", enrolledAt: "2026-07-13", amount: 290000, method: "카드", progress: 90 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v22", name: "장하린", email: "hr.jang@fintechlab.io", enrolledAt: "2026-07-14", amount: 290000, method: "계좌이체", progress: 85 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v24", name: "황보라", email: "br.hwang@brandflow.kr", enrolledAt: "2026-07-15", amount: 290000, method: "카드", progress: 90 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v26", name: "심다빈", email: "db.shim@uxpulse.co", enrolledAt: "2026-07-16", amount: 290000, method: "카카오페이", progress: 95 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v28", name: "오채린", email: "cr.oh@vclink.com", enrolledAt: "2026-07-17", amount: 290000, method: "카드", progress: 80 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v06", name: "강하은", email: "he.kang@designcraft.kr", enrolledAt: "2026-07-18", amount: 290000, method: "카카오페이", progress: 90 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v08", name: "임수아", email: "sa.lim@marketloop.co", enrolledAt: "2026-07-18", amount: 290000, method: "카드", progress: 85 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v09", name: "한지호", email: "jh.han@b2bworks.io", enrolledAt: "2026-07-19", amount: 290000, method: "계좌이체", progress: 80 },
  { courseId: "c-lecto-6", courseTitle: "초보자를 위한 C 프로그래밍 마스터 과정: 기초부터 핵심까지", userId: "m-v10", name: "송채원", email: "cw.song@creativelab.net", enrolledAt: "2026-07-19", amount: 290000, method: "카드", progress: 100 },
];

const SEED_COURSE_STUDENTS: CourseStudent[] = ENROLLMENTS_DEF.map((e, idx) => ({
  id: `cs-${idx + 1}`,
  userId: e.userId,
  name: e.name,
  email: e.email,
  avatar: "",
  courseId: e.courseId,
  courseTitle: e.courseTitle,
  enrolledAt: e.enrolledAt,
  progress: e.progress,
  completed: e.progress >= 90,
  completedAt: e.progress >= 90 ? "2026-08-30" : undefined,
  certificateIssued: e.progress >= 90,
  paymentId: `pay-${idx + 1}`,
  paymentAmount: e.amount,
  paymentStatus: "완료",
  lastActive: "최근 1일 전",
}));

const SEED_PAYMENTS: PaymentRecord[] = ENROLLMENTS_DEF.map((e, idx) => ({
  id: `pay-${idx + 1}`,
  courseId: e.courseId,
  courseTitle: e.courseTitle,
  userId: e.userId,
  amount: e.amount,
  method: e.method,
  date: `${e.enrolledAt} 14:30:00`,
  status: "완료",
}));

// ─────────────────────────────────────────────────────────────
// 4. 스타트업/IR 권장 루틴 (아이디어 의뢰 4종 + 역제안 4종 + IR 프로젝트 4종)
// - 4개 프로젝트: CodeInDocker, 점•선•면 연구소, Lectomate, AX로 창업하라
// - 필수 회원 오승환/마하우가 발제/역제안/IR 팀멤버로 전원 참여
// - 투자 유치 단계: Pre-Seed
// - AX로 창업하라: 팀원 모집 활성화 (isHiring: true)
// ─────────────────────────────────────────────────────────────

const SEED_IDEA_REQUESTS: IdeaRequest[] = [
  {
    id: "ir-req-1",
    title: "CodeInDocker: 개발 구성원 간 소스 환경을 손쉽게 공유하는 협업 플랫폼",
    problem: "신규 팀원 합류 시 로컬 개발 환경(OS, 의존성 패키지, 데이터베이스 버전 등) 세팅에 수일이 소요되며, '내 컴퓨터에선 되는데' 현상으로 인한 버그 디버깅 비용이 큽니다.",
    solutionConcept: "Docker 컨테이너 기반으로 개발 환경을 표준화 패키징하여 웹 브라우저 또는 로컬 IDE에서 원클릭으로 구동할 수 있는 팀 협업 클라우드 개발 플랫폼.",
    category: "개발·IT",
    tags: ["Docker", "클라우드IDE", "개발환경표준화", "협업플랫폼", "DevOps"],
    requiredRoles: ["클라우드 인프라 엔지니어", "프론트엔드 개발자", "Go 백엔드 개발자"],
    rewardType: "지분공유(코파운더)",
    rewardDetail: "지분 15~20% 협의 + 기술 총괄(CTO) 포지션",
    submissionDeadline: "2026-03-15",
    selectionDate: "2026-03-20",
    requestedBy: {
      userId: "m-v11",
      userName: "조은우 (에듀테크 기획)",
      avatar: "",
    },
    upvotes: [
      "m-v11", "m-otter", "m-mahau", "m-v01", "m-v02", "m-v03", "m-v04", "m-v05", "m-v06", "m-v07",
      "m-v08", "m-v09", "m-v10", "m-v12", "m-v13", "m-v14", "m-v15", "m-v16", "m-v17", "m-v18",
      "m-v19", "m-v20", "m-v21", "m-v22", "m-v23", "m-v24", "m-v25", "m-v26"
    ],
    upvoteCount: 28,
    status: "선발진행중",
    selectedProposalIds: ["ip-1"],
    matchedProjectIds: ["p-codeindocker"],
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "ir-req-2",
    title: "점•선•면 연구소: 인문학적 가치와 기술 전문성을 결합한 공간 문화 하이브리드 플랫폼",
    problem: "기술이 일상 공간을 지배하면서 인간다움과 장소의 기억이 소외되고 있으며, 건축가·철학자·엔지니어 간의 유기적인 융합 기획 도구가 부재합니다.",
    solutionConcept: "삶을 담는 그릇으로서의 기술을 설계하고 기술이 머무는 자리에 남겨질 인간의 흔적과 공간 문화를 인터랙티브 3D와 철학적 텍스트로 아카이빙 및 큐레이션하는 플랫폼.",
    category: "디자인/UX",
    tags: ["공간문화", "하이브리드연구", "인문학기술융합", "인터랙티브3D", "공간기록"],
    requiredRoles: ["인터랙티브 웹 엔지니어", "3D 비주얼 디자이너", "콘텐츠 에디터"],
    rewardType: "수익셰어",
    rewardDetail: "프로젝트 런칭 후 파트너십 및 공간 컨설팅 수익 30% 배분",
    submissionDeadline: "2026-04-15",
    selectionDate: "2026-04-20",
    requestedBy: {
      userId: "m-v05",
      userName: "최민재 (공간 기획가)",
      avatar: "",
    },
    upvotes: [
      "m-v05", "m-otter", "m-mahau", "m-v01", "m-v03", "m-v04", "m-v06", "m-v08", "m-v10", "m-v11",
      "m-v12", "m-v14", "m-v15", "m-v17", "m-v18", "m-v20", "m-v22", "m-v24", "m-v26", "m-v27",
      "m-v28", "m-v29", "m-v30", "m-v02", "m-v07", "m-v09"
    ],
    upvoteCount: 26,
    status: "선발진행중",
    selectedProposalIds: ["ip-2"],
    matchedProjectIds: ["p-cocolabhub"],
    createdAt: "2026-03-10T14:30:00Z",
  },
  {
    id: "ir-req-3",
    title: "Lectomate: AI와 협업하여 풍부한 강의 자료를 빠르게 준비하는 교육 자동화 플랫폼",
    problem: "교육자가 강의 계획서, 슬라이드 초안, 실습 예제, 평가 문항을 준비하는 데 수십 시간이 소요되어 정작 창의적인 수업 설계와 학생 피드백에 집중하기 어렵습니다.",
    solutionConcept: "교육자의 핵심 아이디어와 AI 역량을 결합하여 강의계획서, 회차별 실습 자료, 슬라이드를 5분 만에 지능적으로 생성하고 공유하는 차세대 에듀테크 SaaS.",
    category: "AI 모델링",
    tags: ["Lectomate", "에듀테크", "강의기획자동화", "LLM생성", "수업관리SaaS"],
    requiredRoles: ["AI/LLM 엔지니어", "React 풀스택 개발자", "교육 콘텐츠 디자이너"],
    rewardType: "지분공유(코파운더)",
    rewardDetail: "지분 20% 및 공동대표(Co-founder) 지위",
    submissionDeadline: "2026-05-15",
    selectionDate: "2026-05-20",
    requestedBy: {
      userId: "m-v04",
      userName: "정예은 (교육 기획 PM)",
      avatar: "",
    },
    upvotes: [
      "m-v04", "m-otter", "m-mahau", "m-v01", "m-v02", "m-v03", "m-v05", "m-v06", "m-v07", "m-v08",
      "m-v09", "m-v10", "m-v11", "m-v12", "m-v13", "m-v14", "m-v15", "m-v16", "m-v17", "m-v18",
      "m-v19", "m-v20", "m-v21", "m-v22", "m-v23", "m-v24", "m-v25", "m-v26", "m-v27", "m-v28",
      "m-v29", "m-v30", "m-otter", "m-mahau", "m-v02"
    ],
    upvoteCount: 35,
    status: "선발진행중",
    selectedProposalIds: ["ip-3"],
    matchedProjectIds: ["p-lectomate"],
    createdAt: "2026-04-10T09:15:00Z",
  },
  {
    id: "ir-req-4",
    title: "AX로 창업하라: 아이디어부터 투자까지, AI로 빠르게 창업하는 올인원 플랫폼",
    problem: "예비 창업자가 교육 수강, 팀원 모집(팀빌딩), MVP 검증, 투자 유치(IR)를 각각 분절된 플랫폼에서 처리하느라 사업화 검증까지 평균 1년 이상 지체되는 병목이 발생합니다.",
    solutionConcept: "실시간 징검다리 교육, 빌더 역제안 자동 팀 매칭, Pre-Seed 투자 유치 연계까지 창업 전 주기를 AI 에이전트와 함께 원스톱으로 압축 지원하는 액셀러레이팅 플랫폼.",
    category: "비즈니스 기획",
    tags: ["AX창업", "린스타트업", "자동팀매칭", "IR피칭연계", "원스톱창업플랫폼"],
    requiredRoles: ["AI/ML 리드 엔지니어", "시니어 풀스택 개발자", "그로스 마케터"],
    rewardType: "지분공유(코파운더)",
    rewardDetail: "핵심 코파운더 지분 10~20% 협의 + 스톡옵션",
    submissionDeadline: "2026-06-15",
    selectionDate: "2026-06-20",
    requestedBy: {
      userId: "m-v02",
      userName: "박지민 (AI 프로덕트 기획)",
      avatar: "",
    },
    upvotes: [
      "m-v02", "m-otter", "m-mahau", "m-v01", "m-v03", "m-v04", "m-v05", "m-v06", "m-v07", "m-v08",
      "m-v09", "m-v10", "m-v11", "m-v12", "m-v13", "m-v14", "m-v15", "m-v16", "m-v17", "m-v18",
      "m-v19", "m-v20", "m-v21", "m-v22", "m-v23", "m-v24", "m-v25", "m-v26", "m-v27", "m-v28",
      "m-v29", "m-v30", "m-v01", "m-v02", "m-v03", "m-v04", "m-v05", "m-v06", "m-v07", "m-v08",
      "m-v09", "m-v10"
    ],
    upvoteCount: 42,
    status: "선발진행중",
    selectedProposalIds: ["ip-4"],
    matchedProjectIds: ["p-axfoundly"],
    createdAt: "2026-05-10T11:00:00Z",
  },
];

const SEED_IDEA_PROPOSALS: IdeaProposal[] = [
  {
    id: "ip-1",
    requestId: "ir-req-1",
    proposerId: "m-otter",
    proposerName: "오승환",
    proposerAvatar: "",
    teamSummary: "클라우드 컨테이너 인프라 전문가 오승환(CTO) & 시스템 아키텍트 마하우 협업 팀",
    techStack: ["Docker", "Kubernetes", "React", "Node.js", "WebSocket", "Go"],
    planSummary: "3주 만에 웹 브라우저 기반 실시간 터미널 및 Docker 템플릿 환경 완성, 4주차에 팀원 초대 및 환경 공유 기능 MVP 런칭.",
    estimatedWeeks: 4,
    portfolioUrl: "https://codeindocker.com",
    contactEmail: "otter.oh@gmail.com",
    demoVideoUrl: "https://youtu.be/79RMJavIfaA",
    prototypeUrl: "https://codeindocker.com",
    visibility: "public",
    status: "선발(협의중)",
    linkedProjectId: "p-codeindocker",
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "ip-2",
    requestId: "ir-req-2",
    proposerId: "m-otter",
    proposerName: "오승환",
    proposerAvatar: "",
    teamSummary: "테크 리드 오승환 & 공간 철학/인문학 어드바이저 마하우 공동 기획 팀",
    techStack: ["Three.js", "Next.js", "WebGL", "Node.js", "MongoDB"],
    planSummary: "공간 문화 데이터를 3차원 디지털 노드로 시각화하고 철학적 담론을 카드형 저널로 결합한 인터랙티브 공간 아카이빙 플랫폼 구축.",
    estimatedWeeks: 6,
    portfolioUrl: "https://cocolabhub.com",
    contactEmail: "otter.oh@gmail.com",
    prototypeUrl: "https://cocolabhub.com",
    visibility: "public",
    status: "선발(협의중)",
    linkedProjectId: "p-cocolabhub",
    createdAt: "2026-03-25T14:00:00Z",
  },
  {
    id: "ip-3",
    requestId: "ir-req-3",
    proposerId: "m-mahau",
    proposerName: "마하우",
    proposerAvatar: "",
    teamSummary: "교육 AI 시스템 총괄 마하우 & 수석 AI 아키텍트 오승환 연합 빌더 팀",
    techStack: ["Next.js", "FastAPI", "Gemini 2.5", "TailwindCSS", "PostgreSQL"],
    planSummary: "커리큘럼 자동 설계 RAG 파이프라인과 실시간 협업 에디터를 개발하여 강사가 5분 내 고품질 강의 계획서를 뽑아낼 수 있는 SaaS 구현.",
    estimatedWeeks: 4,
    portfolioUrl: "https://www.lectomate.com",
    contactEmail: "mahau.master@gmail.com",
    prototypeUrl: "https://www.lectomate.com",
    visibility: "public",
    status: "선발(협의중)",
    linkedProjectId: "p-lectomate",
    createdAt: "2026-04-25T16:30:00Z",
  },
  {
    id: "ip-4",
    requestId: "ir-req-4",
    proposerId: "m-otter",
    proposerName: "오승환",
    proposerAvatar: "",
    teamSummary: "AX Foundly 대표 오승환 & 운영 총괄 마하우 코어 파운더 팀",
    techStack: ["React 19", "Express", "MongoDB", "Google GenAI", "Playwright"],
    planSummary: "아이디어 발제, 빌더 역제안, 징검다리 교육, 팀 매칭, IR 피칭덱 생성을 아우르는 AI 기반 창업 전 주기 원스톱 솔루션 완성.",
    estimatedWeeks: 8,
    portfolioUrl: "https://www.axfoundly.com",
    contactEmail: "otter.oh@gmail.com",
    prototypeUrl: "https://www.axfoundly.com",
    visibility: "public",
    status: "선발(협의중)",
    linkedProjectId: "p-axfoundly",
    createdAt: "2026-05-25T11:00:00Z",
  },
];

const SEED_IR_PROJECTS: IRProject[] = [
  {
    id: "p-codeindocker",
    teamName: "CodeInDocker",
    anonymousTeamName: "🐳 도커 마스터즈",
    title: "개발 환경의 표준화와 즉각 공유: CodeInDocker 협업 플랫폼",
    oneLiner: "Docker 컨테이너 기반으로 팀 전체가 동일한 개발 환경에서 즉시 작업하는 협업 플랫폼",
    description: "Docker 컨테이너를 기반으로 개발 환경을 패키징하여 팀 전체가 동일한 환경에서 작업합니다. 신규 팀원 온보딩 시간을 수 시간에서 단 몇 분으로 단축하고 환경 불일치로 인한 버그를 원천 차단합니다.",
    field: "개발·IT",
    tags: ["Docker", "클라우드IDE", "개발협업", "DevOps", "B2B SaaS"],
    aiSummary: "컨테이너 기반 원클릭 환경 공유로 팀 온보딩 시간을 분 단위로 단축하는 개발 협업 플랫폼",
    thumbnail: "",
    demoVideoUrl: "https://youtu.be/79RMJavIfaA",
    prototypeUrl: "https://codeindocker.com/",
    isAnonymous: false,
    members: [
      { name: "오승환", role: "CTO / 클라우드 인프라 총괄", avatar: "", bio: "대규모 컨테이너 가상화 및 클라우드 아키텍처 10년차" },
      { name: "마하우", role: "Co-founder / 시스템 아키텍트", avatar: "", bio: "고성능 분산 시스템 및 가상화 파이프라인 전문가" },
      { name: "조은우", role: "기획 리드 / CPO", avatar: "", bio: "에듀테크 및 개발자 생산성 도구 프로덕트 기획" },
    ],
    businessModel: "팀/엔터프라이즈 월 구독 SaaS (유저당 월 $15 ~ $35)",
    problem: "신규 개발자 온보딩 시 환경 설정에 평균 2~3일이 소요되고, OS별 환경 차이로 인한 예상치 못한 배포 버그가 발생함.",
    solution: "브라우저 원클릭 접속 및 동일한 Docker 컨테이너 이미지 공유로 환경 일치율 100% 보장.",
    isHiring: true,
    hiringRoles: ["프론트엔드 엔지니어 (React)", "Go 백엔드 엔지니어"],
    investmentStage: "Pre-Seed",
    createdAt: "2026-03-01T10:00:00Z",
    upvotes: [
      "m-v11", "m-otter", "m-mahau", "m-v01", "m-v02", "m-v03", "m-v04", "m-v05", "m-v06", "m-v07",
      "m-v08", "m-v09", "m-v10", "m-v12", "m-v13", "m-v14", "m-v15", "m-v16", "m-v17", "m-v18",
      "m-v19", "m-v20", "m-v21", "m-v22", "m-v23", "m-v24", "m-v25", "m-v26"
    ],
    upvoteCount: 28,
    authorId: "m-otter",
    authorName: "오승환",
    originIdeaRequestId: "ir-req-1",
    originIdeaTitle: "CodeInDocker: 개발 구성원 간 소스 환경을 손쉽게 공유하는 협업 플랫폼",
    originProposalId: "ip-1",
    visibility: "public",
  },
  {
    id: "p-cocolabhub",
    teamName: "점•선•면 연구소",
    anonymousTeamName: "📐 공간 철학 랩",
    title: "인문학적 가치와 기술 전문성의 만남: 삶을 담는 공간 문화 플랫폼",
    oneLiner: "기술이 보이지 않고 인간다움이 선명해지는 공간 문화 창조를 지향하는 하이브리드 연구 집단",
    description: "건축가, 철학자, 엔지니어가 협업하여 삶을 담는 그릇으로서의 기술을 함께 설계합니다. 기술은 수단이며, 궁극적인 지향점은 인간의 삶의 질 향상과 존엄성 회복에 있습니다. 우리는 기술 그 자체보다 기술이 머무는 자리에 남겨질 인간의 흔적에 집중합니다.",
    field: "디자인/UX",
    tags: ["공간문화", "점선면연구소", "인문학융합", "3D아카이빙", "공간경험"],
    aiSummary: "건축, 철학, 기술을 융합하여 인간다움이 머무는 공간 문화를 디지털로 기록하는 연구 플랫폼",
    thumbnail: "",
    prototypeUrl: "https://cocolabhub.com/",
    isAnonymous: false,
    members: [
      { name: "오승환", role: "기술 총괄 (Tech Lead)", avatar: "", bio: "인터랙티브 웹 시각화 및 데이터 아카이빙 엔진 설계" },
      { name: "마하우", role: "공간 철학 어드바이저", avatar: "", bio: "공간 인문학 및 사용자 경험 가치 설계 멘토" },
      { name: "최민재", role: "대표 / 총괄 기획", avatar: "", bio: "공간 기획 및 문화 프로젝트 디렉터" },
    ],
    businessModel: "공간 문화 디지털 아카이빙 솔루션 라이선스 및 지자체/기업 공간 컨설팅",
    problem: "급격한 디지털화로 인해 오프라인 공간의 역사적 가치와 인문학적 맥락이 손실됨.",
    solution: "3D 공간 데이터와 철학적 내러티브를 결합한 지속 가능한 인터랙티브 공간 아카이빙.",
    isHiring: false,
    investmentStage: "Pre-Seed",
    createdAt: "2026-03-25T14:00:00Z",
    upvotes: [
      "m-v05", "m-otter", "m-mahau", "m-v01", "m-v03", "m-v04", "m-v06", "m-v08", "m-v10", "m-v11",
      "m-v12", "m-v14", "m-v15", "m-v17", "m-v18", "m-v20", "m-v22", "m-v24", "m-v26", "m-v27",
      "m-v28", "m-v29", "m-v30", "m-v02", "m-v07", "m-v09"
    ],
    upvoteCount: 26,
    authorId: "m-otter",
    authorName: "오승환",
    originIdeaRequestId: "ir-req-2",
    originIdeaTitle: "점•선•면 연구소: 인문학적 가치와 기술 전문성을 결합한 공간 문화 하이브리드 플랫폼",
    originProposalId: "ip-2",
    visibility: "public",
  },
  {
    id: "p-lectomate",
    teamName: "Lectomate",
    anonymousTeamName: "🎓 에듀테크 AI",
    title: "AI와 협업하여 풍부한 강의 자료를 빠르게 준비하는 교육 자동화 플랫폼",
    oneLiner: "교육자의 아이디어와 AI 능력을 결합하여 강의 계획서와 학습 자료를 신속하게 생성하는 SaaS",
    description: "교육자의 아이디어와 AI 능력을 결합하여 강의 계획서, 슬라이드, 학습 자료를 신속하게 생성합니다. 교육자가 창의적인 수업 설계에 집중할 수 있도록 반복 작업을 지능적으로 자동화합니다.",
    field: "AI 모델링",
    tags: ["Lectomate", "에듀테크", "강의계획서자동화", "교육SaaS", "AI수업설계"],
    aiSummary: "수업 기획부터 슬라이드 초안까지 교육자의 반복 업무를 80% 줄여주는 지능형 교육 자동화 SaaS",
    thumbnail: "",
    prototypeUrl: "https://www.lectomate.com/",
    isAnonymous: false,
    members: [
      { name: "마하우", role: "대표 (CEO) & 교육 AI 총괄", avatar: "", bio: "교육 공학 및 생성형 AI 교육 솔루션 10년 경력" },
      { name: "오승환", role: "수석 AI 아키텍트 (Chief AI Architect)", avatar: "", bio: "LLM 오케스트레이션 및 에이전트 시스템 전문가" },
      { name: "정예은", role: "프로덕트 리드 (CPO)", avatar: "", bio: "스타트업 에듀테크 PM 및 커리큘럼 설계 전문가" },
    ],
    businessModel: "강사 및 기관 대상 B2B/B2C 구독형 요금제 (월 29,000원 ~ 190,000원)",
    problem: "강의 한 과목 개설 시 커리큘럼 및 교재 준비에 최소 40시간 이상의 단순 반복 작업이 소요됨.",
    solution: "검증된 교육 프롬프트 파이프라인과 RAG를 통해 5분 만에 맞춤형 커리큘럼과 회차별 학습 자료 생성.",
    isHiring: true,
    hiringRoles: ["AI 프롬프트 엔지니어", "프론트엔드 (Next.js)"],
    investmentStage: "Pre-Seed",
    createdAt: "2026-04-25T16:30:00Z",
    upvotes: [
      "m-v04", "m-otter", "m-mahau", "m-v01", "m-v02", "m-v03", "m-v05", "m-v06", "m-v07", "m-v08",
      "m-v09", "m-v10", "m-v11", "m-v12", "m-v13", "m-v14", "m-v15", "m-v16", "m-v17", "m-v18",
      "m-v19", "m-v20", "m-v21", "m-v22", "m-v23", "m-v24", "m-v25", "m-v26", "m-v27", "m-v28",
      "m-v29", "m-v30", "m-otter", "m-mahau", "m-v02"
    ],
    upvoteCount: 35,
    authorId: "m-mahau",
    authorName: "마하우",
    originIdeaRequestId: "ir-req-3",
    originIdeaTitle: "Lectomate: AI와 협업하여 풍부한 강의 자료를 빠르게 준비하는 교육 자동화 플랫폼",
    originProposalId: "ip-3",
    visibility: "public",
  },
  {
    id: "p-axfoundly",
    teamName: "AX로 창업하라",
    anonymousTeamName: "🚀 AX Foundly 파운더스",
    title: "아이디어부터 투자까지, AI로 빠르게 창업하라 (AX Foundly)",
    oneLiner: "실시간 징검다리 교육, 자동 팀 매칭, 투자 유치 연계까지 창업의 전 과정을 원스톱으로 지원",
    description: "아이디어부터 투자까지, AI로 빠르게 창업하라. 실시간 징검다리 교육, 자동 팀 매칭, 투자 유치 연계까지 창업의 전 과정을 원스톱으로 지원합니다.",
    field: "비즈니스 기획",
    tags: ["AX창업", "린스타트업", "자동팀매칭", "IR연계", "원스톱창업플랫폼"],
    aiSummary: "아이디어 발제, 역제안 매칭, 징검다리 실전 교육, 투자 유치를 하나로 잇는 원스톱 스타트업 플랫폼",
    thumbnail: "",
    prototypeUrl: "https://www.axfoundly.com/",
    isAnonymous: false,
    members: [
      { name: "오승환", role: "대표 (CEO) & AI 엔지니어링 리드", avatar: "", bio: "AX Foundly 파운더, 에이전틱 개발 및 린 스타트업 전문가" },
      { name: "마하우", role: "공동대표 (Co-founder) & 운영 총괄", avatar: "", bio: "플랫폼 파트너십 및 교육/액셀러레이팅 총괄" },
      { name: "박지민", role: "프로덕트 기획 (Head of Product)", avatar: "", bio: "초기 스타트업 PM 및 AI 제품 런칭 전문가" },
    ],
    businessModel: "교육 수강 수수료, 팀빌딩 프리미엄 매칭, 투자 유치 성공 보수",
    problem: "초기 창업팀이 교육, 팀빌딩, 시제품 제작, IR 피칭을 각기 다른 채널에서 진행하며 겪는 극심한 시간·자본 낭비.",
    solution: "아이디어 의뢰와 빌더 역제안이 결합된 마켓플레이스 + 하네스 기반 AI 에이전트 자율 지원 파이프라인.",
    isHiring: true,
    hiringRoles: ["AI/ML 파이프라인 엔지니어", "시니어 풀스택 개발자 (React/Node)", "프로덕트 그로스 마케터"],
    hiringDetails: [
      {
        id: "hr-ax-1",
        role: "AI/ML 파이프라인 엔지니어 (Co-founder 레벨)",
        type: "코파운더",
        compensation: "월 350만원 + 지분 협의",
        equity: "5.0% ~ 15.0%",
        skills: ["Python", "LangChain", "Google GenAI", "MongoDB", "Docker"],
        applyMethod: "internal",
        description: "창업 아이디어 분류, 역제안 추천 및 자동 IR 피칭덱 생성 LLM 파이프라인을 구축합니다.",
      },
      {
        id: "hr-ax-2",
        role: "시니어 풀스택 개발자 (React / Express / MongoDB)",
        type: "풀타임",
        compensation: "연봉 6,500 ~ 8,500만원",
        equity: "1.0% ~ 3.0%",
        skills: ["React 19", "TypeScript", "Node.js", "Express", "TailwindCSS"],
        applyMethod: "internal",
        description: "원스톱 플랫폼의 핵심 유저 저니(교육 수강신청, 결제, IR 피칭, 팀빌딩)를 개발하고 최적화합니다.",
      },
      {
        id: "hr-ax-3",
        role: "프로덕트 그로스 마케터",
        type: "파트타임",
        compensation: "시급 35,000원 또는 월 250만원 (협의)",
        skills: ["퍼널 분석", "콘텐츠 마케팅", "커뮤니티 빌딩", "GA4"],
        applyMethod: "internal",
        description: "초기 예비 창업자 및 빌더 커뮤니티 유입을 촉진하고 AARRR 지표를 개선합니다.",
      },
    ],
    investmentStage: "Pre-Seed",
    createdAt: "2026-05-25T11:00:00Z",
    upvotes: [
      "m-v02", "m-otter", "m-mahau", "m-v01", "m-v03", "m-v04", "m-v05", "m-v06", "m-v07", "m-v08",
      "m-v09", "m-v10", "m-v11", "m-v12", "m-v13", "m-v14", "m-v15", "m-v16", "m-v17", "m-v18",
      "m-v19", "m-v20", "m-v21", "m-v22", "m-v23", "m-v24", "m-v25", "m-v26", "m-v27", "m-v28",
      "m-v29", "m-v30", "m-v01", "m-v02", "m-v03", "m-v04", "m-v05", "m-v06", "m-v07", "m-v08",
      "m-v09", "m-v10"
    ],
    upvoteCount: 42,
    authorId: "m-otter",
    authorName: "오승환",
    originIdeaRequestId: "ir-req-4",
    originIdeaTitle: "AX로 창업하라: 아이디어부터 투자까지, AI로 빠르게 창업하는 올인원 플랫폼",
    originProposalId: "ip-4",
    visibility: "public",
  },
];

// ─────────────────────────────────────────────────────────────
// 5. 커뮤니티 게시글 및 댓글 (BoardPost & Comment)
// ─────────────────────────────────────────────────────────────

const SEED_POSTS: BoardPost[] = [
  {
    id: "post-1",
    boardType: "공지사항",
    title: "[공지] 2026 상반기 AI 린 스타트업 챌린지 및 IR 데모데이 안내",
    content: "안녕하세요, AX Foundly 운영진입니다.\n2026년 3월부터 8월까지 교육 과정을 이수하고 아이디어 역제안을 통해 결성된 팀들을 대상으로 Pre-Seed IR 데모데이를 개최합니다.\n많은 참여 부탁드립니다.",
    author: "마하우",
    authorAvatar: "",
    authorRoles: ["admin", "member"],
    createdAt: "2026-08-01 10:00",
    viewCount: 342,
    commentCount: 4,
    isPinned: true,
  },
  {
    id: "post-2",
    boardType: "팀빌딩",
    title: "AX로 창업하라 팀에서 AI/ML 파이프라인 엔지니어를 모십니다 (Pre-Seed)",
    content: "AX Foundly 코어 팀에서 창업 아이디어 분류 및 자동 IR 피칭 파이프라인을 함께 구축할 엔지니어를 찾고 있습니다.\n상세 구인 공고는 스타트업 IR 탭에서 확인하실 수 있습니다!",
    author: "오승환",
    authorAvatar: "",
    authorRoles: ["admin", "member"],
    createdAt: "2026-08-05 14:20",
    viewCount: 280,
    commentCount: 3,
    isPinned: true,
  },
  {
    id: "post-3",
    boardType: "QnA",
    title: "하네스 엔지니어링 마스터 클래스 수료 후 실무 적용 팁 공유합니다",
    content: "오승환 강사님의 하네스 강의를 완강하고 사내 에이전트에 자가 치유 루프를 적용했습니다.\n혹시 LangGraph 연동 시 상태 영속화 관련 팁이 더 필요하신 분 계신가요?",
    author: "문지아",
    authorAvatar: "",
    authorRoles: ["member"],
    createdAt: "2026-08-10 16:45",
    viewCount: 195,
    commentCount: 2,
    isPinned: false,
  },
];

const SEED_COMMENTS: Comment[] = [
  {
    id: "com-1",
    postId: "post-1",
    author: "오승환",
    authorAvatar: "",
    authorRoles: ["admin", "member"],
    content: "훌륭한 팀들이 많이 참여해 주시기를 기대합니다. 멘토링도 아낌없이 지원하겠습니다.",
    createdAt: "2026-08-01 11:30",
  },
  {
    id: "com-2",
    postId: "post-1",
    author: "김서준",
    authorAvatar: "",
    authorRoles: ["member"],
    content: "데모데이 피칭 심사 기준에 기술적 완성도 외에 비즈니스 지표도 포함되나요?",
    createdAt: "2026-08-01 13:10",
  },
  {
    id: "com-3",
    postId: "post-2",
    author: "이도윤",
    authorAvatar: "",
    authorRoles: ["member"],
    content: "풀스택 포지션으로 지원서 제출했습니다! 함께 일할 수 있는 기회가 되기를 희망합니다.",
    createdAt: "2026-08-06 09:15",
  },
  {
    id: "com-4",
    postId: "post-3",
    author: "오승환",
    authorAvatar: "",
    authorRoles: ["admin", "member"],
    content: "문지아 님, 자가 치유 루프를 실무에 잘 녹여내셨군요! Checkpointer 관련 팁도 게시글로 추가 공유해 드리겠습니다.",
    createdAt: "2026-08-10 18:00",
  },
];

// ─────────────────────────────────────────────────────────────
// 6. 알림 로그 (Notifications)
// ─────────────────────────────────────────────────────────────

const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    type: "team",
    category: "team",
    title: "빌더 역제안 선발 완료 (IR 연동)",
    message: "'CodeInDocker' 아이디어 의뢰에 오승환 팀의 제안서가 선발팀으로 지정되어 Pre-Seed IR에 등록되었습니다.",
    time: "2026-03-20 10:00",
    isRead: true,
    actionLabel: "IR 프로젝트 보기",
    targetUrl: "/ir?projectId=p-codeindocker",
  },
  {
    id: "notif-2",
    type: "course",
    category: "course",
    title: "강좌 수료 및 수료증 발급 안내",
    message: "'피지컬 AI 및 로보틱스 전문가 양성 과정'을 성공적으로 수료하셨습니다. 수료증이 발급되었습니다.",
    time: "2026-06-15 14:00",
    isRead: true,
    actionLabel: "수료증 확인",
    targetUrl: "/mypage",
  },
  {
    id: "notif-3",
    type: "team",
    category: "team",
    title: "AX로 창업하라 팀원 지원서 접수",
    message: "이도윤 님이 '시니어 풀스택 개발자' 포지션에 지원서를 제출했습니다.",
    time: "2026-08-06 09:15",
    isRead: false,
    actionLabel: "지원서 검토",
    targetUrl: "/ir?projectId=p-axfoundly",
  },
  {
    id: "notif-4",
    type: "course",
    category: "course",
    title: "강의 결제 완료 안내",
    message: "'Copilot과 Jira 연동을 통한 개발 워크플로우 혁신' 결제가 정상 처리되었습니다.",
    time: "2026-07-06 14:30",
    isRead: true,
    actionLabel: "강의실 바로가기",
    targetUrl: "/courses",
  },
];

// ─────────────────────────────────────────────────────────────
// 7. 기타 보조 데이터 (Requests, Proposals, Stats 등)
// ─────────────────────────────────────────────────────────────

const SEED_COURSE_REQUESTS: CourseRequest[] = [
  {
    id: "cr-1",
    title: "실전 LangGraph 기반 멀티 에이전트 자율 코딩 시스템 개강 요청",
    description: "단순 프롬프트 엔지니어링을 넘어 LangGraph 기반 상태 관리, 서브에이전트 조율, 코드 자가 수정 루프를 직접 구현하는 심화 강의를 열어주세요!",
    category: "AI 모델링",
    tags: ["LangGraph", "MultiAgent", "AgenticDev", "Python"],
    targetLevel: "중급",
    preferredSchedule: "평일 저녁 (화/목 19:30~21:30)",
    expectedPriceRange: "40~60만원대",
    requestedBy: {
      userId: "m-v01",
      userName: "김서준",
      avatar: "",
    },
    upvotes: ["m-v01", "m-otter", "m-mahau", "m-v02", "m-v03", "m-v07", "m-v16", "m-v23", "m-v25"],
    upvoteCount: 9,
    targetCount: 15,
    status: "강사매칭중",
    createdAt: "2026-08-15T10:00:00Z",
  },
];

const SEED_COURSE_PROPOSALS: CourseProposal[] = [
  {
    id: "cp-1",
    requestId: "cr-1",
    instructorId: "m-otter",
    instructorName: "오승환",
    instructorAvatar: "",
    instructorTitle: "AX Foundly 대표 & 테크 리드",
    proposedTitle: "LangGraph & Claude Code 기반 자율 에이전트 개발 실전 4주",
    curriculumDraft: [
      "1회차: LangGraph 그래프 구조와 StateGraph 설계 패턴",
      "2회차: Tool Calling 및 브라우저/터미널 샌드박스 연동",
      "3회차: 체크포인터(Checkpointer)와 휴먼 인 더 루프(HITL) 설계",
      "4회차: 상용 환경 모니터링 및 LangSmith 벤치마크",
    ],
    proposedPrice: 490000,
    proposedSchedule: "매주 화/목 20:00~22:00 (총 8회차 / 4주)",
    message: "안녕하세요 김서준 님, 실무에서 바로 쓸 수 있는 검증된 LangGraph 아키텍처로 커리큘럼을 준비했습니다.",
    status: "대기중",
    createdAt: "2026-08-18T14:00:00Z",
  },
];

const SEED_TEAM_REQUESTS: TeamBuildingRequest[] = [
  {
    id: "tr-1",
    type: "received",
    projectName: "AX로 창업하라",
    fromUser: "이도윤 (풀스택 개발자)",
    toUser: "오승환",
    role: "시니어 풀스택 개발자",
    message: "Next.js와 Node.js 기반 B2B SaaS 개발 5년차입니다. 플랫폼 확장에 기여하고 싶습니다.",
    status: "대기중",
    date: "2026-08-06",
  },
  {
    id: "tr-2",
    type: "sent",
    projectName: "CodeInDocker",
    fromUser: "오승환",
    toUser: "안우진 (엣지 AI 엔지니어)",
    role: "Go 백엔드 및 컨테이너 최적화",
    message: "Docker 가상화 파이프라인 개발에 우진 님의 시스템 프로그래밍 역량이 큰 도움이 될 것 같습니다.",
    status: "수락",
    date: "2026-03-22",
  },
];

const SEED_PROPOSALS: InvestmentProposal[] = [
  {
    id: "prop-1",
    projectId: "p-axfoundly",
    projectName: "AX로 창업하라",
    message: "귀사의 역제안 기반 창업 파이프라인 모델을 매우 인상 깊게 보았습니다. Pre-Seed 투자 유치 관련 1차 티타임을 요청드립니다.",
    sentDate: "2026-08-20",
    status: "수락",
  },
];

const SEED_RECOMMENDATIONS: AIRecommendation[] = [
  {
    projectId: "p-axfoundly",
    projectName: "AX로 창업하라",
    matchScore: 98,
    matchReasons: ["교육-빌더-투자 원스톱 생태계", "기술 총괄 및 창업팀 역량 우수", "린 스타트업 MVP 검증 완료"],
    field: "비즈니스 기획",
  },
  {
    projectId: "p-codeindocker",
    projectName: "CodeInDocker",
    matchScore: 94,
    matchReasons: ["개발 환경 불일치 페인포인트 해소", "컨테이너 가상화 기술 경쟁력", "팀 온보딩 시간 90% 절감"],
    field: "개발·IT",
  },
];

const SEED_STATS: DashboardStats = {
  dailySignups: 4,
  monthlySignups: 32,
  totalRevenue: 52440000,
  monthlyRevenue: 12800000,
  activeCourses: 6,
  teamMatchCount: 8,
  investmentMatchCount: 4,
  courseRequestCount: 1,
  courseMatchRate: 100,
  ideaRequestCount: 4,
  builderMatchRate: 100,
  aiAutoFillCount: 38,
};

const SEED_BOARDS: AdminBoard[] = [
  { id: "b1", name: "공지사항", readPermission: "전체", writePermission: "관리자", template: "일반형", postCount: 15, createdAt: "2026-01-01" },
  { id: "b2", name: "팀 빌딩 (Co-founder)", readPermission: "회원", writePermission: "회원", template: "카드형", postCount: 42, createdAt: "2026-01-01" },
  { id: "b3", name: "Q&A 자유게시판", readPermission: "전체", writePermission: "회원", template: "일반형", postCount: 88, createdAt: "2026-01-01" },
];

const SEED_CRM_MESSAGES: CRMMessage[] = [
  {
    id: "crm-1",
    courseId: "c-lecto-3",
    courseTitle: "AI 에이전트 성능의 핵심 - 하네스 엔지니어링 마스터 클래스",
    targetType: "all",
    targetCount: 18,
    title: "수료증 발급 및 추가 리소스 안내",
    content: "수강생 여러분, 하네스 엔지니어링 마스터 클래스를 완주해 주셔서 감사드립니다. 최종 실습 소스코드가 공유되었습니다.",
    channels: ["inapp", "email"],
    sentAt: "2026-07-16 10:00",
  },
];

const SEED_SETTLEMENTS: SettlementRecord[] = [
  {
    id: "stl-1",
    period: "2026-06",
    totalRevenue: 13860000,
    pgFee: 415800,
    platformFee: 1386000,
    netAmount: 12058200,
    status: "정산완료",
  },
  {
    id: "stl-2",
    period: "2026-07",
    totalRevenue: 10620000,
    pgFee: 318600,
    platformFee: 1062000,
    netAmount: 9239400,
    status: "정산완료",
  },
];

const SEED_NOTIFICATION_PREFERENCES: NotificationPreference[] = [
  {
    userId: "m-otter",
    emailEnabled: true,
    inAppEnabled: true,
    alimtalkEnabled: true,
    categories: {
      course: { inapp: true, email: true, alimtalk: true },
      team: { inapp: true, email: true, alimtalk: true },
      investor: { inapp: true, email: true, alimtalk: true },
      community: { inapp: true, email: false, alimtalk: false },
      digest: { inapp: true, email: true, alimtalk: false },
      marketing: { inapp: false, email: false, alimtalk: false },
    },
    quietHours: { enabled: true, start: "22:00", end: "08:00" },
    updatedAt: "2026-01-01T00:00:00Z",
  },
];

const SEED_NOTIFICATION_TEMPLATES: NotificationTemplate[] = [
  {
    id: "nt-1",
    code: "TEAM_APPLICATION",
    name: "팀원 지원서 접수 알림",
    category: "team",
    titleTemplate: "{{projectName}} 팀원 지원서 접수",
    contentTemplate: "{{applicantName}} 님이 {{role}} 포지션에 지원했습니다.",
    targetUrlTemplate: "/ir?projectId={{projectId}}",
    actionLabelTemplate: "지원서 검토",
    channels: ["inapp", "email"],
  },
];

const SEED_NOTIFICATION_LOGS: NotificationLog[] = [];

// ─────────────────────────────────────────────────────────────
// 8. 공통 코드 & 코드 그룹 (CodeGroups & CommonCodes - 완전 보존)
// ─────────────────────────────────────────────────────────────

const SEED_CODE_GROUPS: CodeGroup[] = [
  {
    groupCode: "INVESTMENT_STAGE",
    groupName: "투자 유치 단계",
    description: "스타트업의 현재 펀딩 라운드 단계",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "EMPLOYMENT_TYPE",
    groupName: "고용 형태",
    description: "창업팀 구인 공고의 고용 및 참여 형태",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "COURSE_CATEGORY",
    groupName: "강의 카테고리",
    description: "교육/강의 등록 및 추천 카테고리 분류",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "COURSE_STATUS",
    groupName: "강의 상태",
    description: "강의 모집 및 진행 단계 상태",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "IR_FIELD",
    groupName: "스타트업 산업/기술 분야",
    description: "스타트업 IR 프로젝트의 산업 도메인 분류",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "PAY_METHOD",
    groupName: "결제 수단",
    description: "강의 수강신청 결제 수단",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "SETTLEMENT_STATUS",
    groupName: "정산 상태",
    description: "강사 수강료 정산 및 출금 처리 상태",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "COURSE_DELIVERY_TYPE",
    groupName: "강의 진행 방식",
    description: "온라인/오프라인/VOD/하이브리드 등 강의 진행 형식 분류",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "USER_STATUS",
    groupName: "회원 상태",
    description: "회원의 활동 가능 상태 (활성=모든 활동, 정지/탈퇴/가상활성=읽기 전용)",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    groupCode: "USER_ROLE",
    groupName: "회원 역할/권한",
    description: "시스템 접근 및 운영 역할 (일반 회원, 매니저, 최고 관리자)",
    isSystem: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
];

const SEED_COMMON_CODES: CommonCode[] = [
  // ── COURSE_DELIVERY_TYPE ──
  {
    id: "cc-deliv-1",
    groupCode: "COURSE_DELIVERY_TYPE",
    code: "ONLINE",
    codeName: "실시간 온라인",
    displayName: "💻 실시간 온라인",
    sortOrder: 1,
    extraValue: { badgeColor: "cyan", icon: "video" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-deliv-2",
    groupCode: "COURSE_DELIVERY_TYPE",
    code: "OFFLINE",
    codeName: "현장 오프라인",
    displayName: "🏢 현장 오프라인",
    sortOrder: 2,
    extraValue: { badgeColor: "amber", icon: "map-pin" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-deliv-3",
    groupCode: "COURSE_DELIVERY_TYPE",
    code: "VOD",
    codeName: "VOD 동영상",
    displayName: "🎥 VOD 동영상",
    sortOrder: 3,
    extraValue: { badgeColor: "purple", icon: "play-circle" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-deliv-4",
    groupCode: "COURSE_DELIVERY_TYPE",
    code: "HYBRID",
    codeName: "온·오프라인 혼합",
    displayName: "🔄 온·오프라인 혼합",
    sortOrder: 4,
    extraValue: { badgeColor: "emerald", icon: "layers" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── INVESTMENT_STAGE ──
  {
    id: "cc-inv-1",
    groupCode: "INVESTMENT_STAGE",
    code: "PRE_SEED",
    codeName: "Pre-Seed",
    displayName: "Pre-Seed",
    sortOrder: 1,
    extraValue: { badgeColor: "amber" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-inv-2",
    groupCode: "INVESTMENT_STAGE",
    code: "SEED",
    codeName: "Seed",
    displayName: "Seed",
    sortOrder: 2,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-inv-3",
    groupCode: "INVESTMENT_STAGE",
    code: "PRE_A",
    codeName: "Pre-A",
    displayName: "Pre-A",
    sortOrder: 3,
    extraValue: { badgeColor: "cyan" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-inv-4",
    groupCode: "INVESTMENT_STAGE",
    code: "SERIES_A",
    codeName: "Series A",
    displayName: "Series A",
    sortOrder: 4,
    extraValue: { badgeColor: "indigo" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── EMPLOYMENT_TYPE ──
  {
    id: "cc-emp-1",
    groupCode: "EMPLOYMENT_TYPE",
    code: "FULL_TIME",
    codeName: "풀타임",
    displayName: "정규직 (풀타임)",
    sortOrder: 1,
    extraValue: { badgeColor: "blue" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-emp-2",
    groupCode: "EMPLOYMENT_TYPE",
    code: "PART_TIME",
    codeName: "파트타임",
    displayName: "파트타임",
    sortOrder: 2,
    extraValue: { badgeColor: "cyan" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-emp-3",
    groupCode: "EMPLOYMENT_TYPE",
    code: "INTERN",
    codeName: "인턴",
    displayName: "인턴십",
    sortOrder: 3,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-emp-4",
    groupCode: "EMPLOYMENT_TYPE",
    code: "CO_FOUNDER",
    codeName: "코파운더",
    displayName: "공동 창업자 (지분 공유)",
    sortOrder: 4,
    extraValue: { badgeColor: "purple" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── COURSE_CATEGORY ──
  {
    id: "cc-cat-1",
    groupCode: "COURSE_CATEGORY",
    code: "AI_MODELING",
    codeName: "AI 모델링",
    displayName: "AI 모델링 & 에이전트",
    sortOrder: 1,
    extraValue: { badgeColor: "cyan" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-cat-2",
    groupCode: "COURSE_CATEGORY",
    code: "DEV_IT",
    codeName: "개발·IT",
    displayName: "개발 & IT 엔지니어링",
    sortOrder: 2,
    extraValue: { badgeColor: "indigo" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-cat-3",
    groupCode: "COURSE_CATEGORY",
    code: "BIZ_PLANNING",
    codeName: "비즈니스 기획",
    displayName: "비즈니스 기획 & BM",
    sortOrder: 3,
    extraValue: { badgeColor: "amber" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-cat-4",
    groupCode: "COURSE_CATEGORY",
    code: "MARKETING_GROWTH",
    codeName: "마케팅·그로스",
    displayName: "마케팅 & 그로스해킹",
    sortOrder: 4,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-cat-5",
    groupCode: "COURSE_CATEGORY",
    code: "DESIGN_UX",
    codeName: "디자인/UX",
    displayName: "UI/UX & 프로덕트 디자인",
    sortOrder: 5,
    extraValue: { badgeColor: "rose" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── COURSE_STATUS ──
  {
    id: "cc-cst-1",
    groupCode: "COURSE_STATUS",
    code: "RECRUITING",
    codeName: "모집중",
    displayName: "모집중",
    sortOrder: 1,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-cst-2",
    groupCode: "COURSE_STATUS",
    code: "IN_PROGRESS",
    codeName: "진행중",
    displayName: "진행중",
    sortOrder: 2,
    extraValue: { badgeColor: "blue" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-cst-3",
    groupCode: "COURSE_STATUS",
    code: "COMPLETED",
    codeName: "종료",
    displayName: "종료",
    sortOrder: 3,
    extraValue: { badgeColor: "slate" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── IR_FIELD ──
  {
    id: "cc-irf-1",
    groupCode: "IR_FIELD",
    code: "AI_DEEPTECH",
    codeName: "AI/딥테크",
    displayName: "인공지능 & 딥테크",
    sortOrder: 1,
    extraValue: { badgeColor: "cyan" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-irf-2",
    groupCode: "IR_FIELD",
    code: "BIO_HEALTH",
    codeName: "바이오·헬스",
    displayName: "디지털 헬스케어 & 바이오",
    sortOrder: 2,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-irf-3",
    groupCode: "IR_FIELD",
    code: "FINTECH",
    codeName: "핀테크",
    displayName: "금융 & 핀테크",
    sortOrder: 3,
    extraValue: { badgeColor: "amber" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-irf-4",
    groupCode: "IR_FIELD",
    code: "B2B_SAAS",
    codeName: "B2B SaaS",
    displayName: "B2B 엔터프라이즈 SaaS",
    sortOrder: 4,
    extraValue: { badgeColor: "indigo" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── PAY_METHOD ──
  {
    id: "cc-pay-1",
    groupCode: "PAY_METHOD",
    code: "CARD",
    codeName: "신용/체크카드",
    displayName: "💳 신용/체크카드",
    sortOrder: 1,
    extraValue: { badgeColor: "blue" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-pay-2",
    groupCode: "PAY_METHOD",
    code: "KAKAO_PAY",
    codeName: "카카오페이",
    displayName: "🟡 카카오페이",
    sortOrder: 2,
    extraValue: { badgeColor: "amber" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-pay-3",
    groupCode: "PAY_METHOD",
    code: "BANK_TRANSFER",
    codeName: "실시간 계좌이체",
    displayName: "🏦 실시간 계좌이체",
    sortOrder: 3,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── SETTLEMENT_STATUS ──
  {
    id: "cc-set-1",
    groupCode: "SETTLEMENT_STATUS",
    code: "PENDING",
    codeName: "정산대기",
    displayName: "정산 대기중",
    sortOrder: 1,
    extraValue: { badgeColor: "amber" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-set-2",
    groupCode: "SETTLEMENT_STATUS",
    code: "REQUESTED",
    codeName: "출금신청",
    displayName: "출금 신청완료",
    sortOrder: 2,
    extraValue: { badgeColor: "blue" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-set-3",
    groupCode: "SETTLEMENT_STATUS",
    code: "COMPLETED",
    codeName: "정산완료",
    displayName: "정산 지급완료",
    sortOrder: 3,
    extraValue: { badgeColor: "emerald" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── USER_STATUS ──
  {
    id: "cc-ust-1",
    groupCode: "USER_STATUS",
    code: "ACTIVE",
    codeName: "활성",
    displayName: "🟢 활성 (모든 활동 가능)",
    sortOrder: 1,
    extraValue: { badgeColor: "emerald", readOnly: false },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-ust-2",
    groupCode: "USER_STATUS",
    code: "SUSPENDED",
    codeName: "정지",
    displayName: "🟡 정지 (읽기만 가능)",
    sortOrder: 2,
    extraValue: { badgeColor: "amber", readOnly: true },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-ust-3",
    groupCode: "USER_STATUS",
    code: "WITHDRAWN",
    codeName: "탈퇴",
    displayName: "🔴 탈퇴 (읽기만 가능)",
    sortOrder: 3,
    extraValue: { badgeColor: "rose", readOnly: true },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-ust-4",
    groupCode: "USER_STATUS",
    code: "VIRTUAL_ACTIVE",
    codeName: "가상활성",
    displayName: "🟣 가상활성 (읽기만 가능)",
    sortOrder: 4,
    extraValue: { badgeColor: "indigo", readOnly: true },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  // ── USER_ROLE ──
  {
    id: "cc-urole-1",
    groupCode: "USER_ROLE",
    code: "MEMBER",
    codeName: "일반 회원",
    displayName: "일반 회원 (member)",
    sortOrder: 1,
    extraValue: { roleKey: "member", badgeColor: "cyan" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-urole-2",
    groupCode: "USER_ROLE",
    code: "MANAGER",
    codeName: "운영 매니저",
    displayName: "운영 매니저 (manager)",
    sortOrder: 2,
    extraValue: { roleKey: "manager", badgeColor: "amber" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "cc-urole-3",
    groupCode: "USER_ROLE",
    code: "ADMIN",
    codeName: "최고 관리자",
    displayName: "최고 관리자 (admin)",
    sortOrder: 3,
    extraValue: { roleKey: "admin", badgeColor: "rose" },
    isActive: true,
    isSystem: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
];

// ─────────────────────────────────────────────────────────────
// 9. 초기 시드 데이터 반환 팩토리
// ─────────────────────────────────────────────────────────────

export function buildSeedData(): DatabaseSchema {
  return {
    courses: SEED_COURSES,
    instructors: SEED_INSTRUCTORS,
    courseStudents: SEED_COURSE_STUDENTS,
    courseRequests: SEED_COURSE_REQUESTS,
    courseProposals: SEED_COURSE_PROPOSALS,
    irProjects: SEED_IR_PROJECTS,
    ideaRequests: SEED_IDEA_REQUESTS,
    ideaProposals: SEED_IDEA_PROPOSALS,
    posts: SEED_POSTS,
    comments: SEED_COMMENTS,
    notifications: SEED_NOTIFICATIONS,
    notificationPreferences: SEED_NOTIFICATION_PREFERENCES,
    notificationTemplates: SEED_NOTIFICATION_TEMPLATES,
    notificationLogs: SEED_NOTIFICATION_LOGS,
    teamRequests: SEED_TEAM_REQUESTS,
    payments: SEED_PAYMENTS,
    settlements: SEED_SETTLEMENTS,
    proposals: SEED_PROPOSALS,
    recommendations: SEED_RECOMMENDATIONS,
    stats: SEED_STATS,
    members: SEED_MEMBERS,
    boards: SEED_BOARDS,
    crmMessages: SEED_CRM_MESSAGES,
    applications: [],
    codeGroups: SEED_CODE_GROUPS,
    commonCodes: SEED_COMMON_CODES,
    kakao_sessions: [],
  };
}
